
version: 1.0.{build}
configuration: Debug
platform: x64
image:
  - macos-bigsur
  - macos
  - Visual Studio 2022
  - Visual Studio 2019
  - Visual Studio 2015

for:
  -
    matrix:
      only:
        - image: macos-bigsur

    build_script:
      - mkdir build_imebra_macos
      - mkdir build_imebra_ios

      - cd build_imebra_macos
      - cmake -GXcode -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build . --config Release
      - ctest -V .

      - cd ../build_imebra_ios
      - cmake -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build . --config Release
      - cmake --build . --config Release -- -sdk iphonesimulator
      - cd ..

    artifacts:
      - path: build_imebra_macos/Release/libimebra.5.*.*.dylib
        name: build_imebra_macos
      - path: build_imebra_ios/Release-iphoneos/libimebra.a
        name: imebra_ios
      - path: build_imebra_ios/Release-iphonesimulator/libimebra.a
        name: imebra_ios_simulator

  -
    matrix:
      only:
        - image: macos

    build_script:
      - mkdir build_imebra_macos

      - cd build_imebra_macos
      - cmake -GXcode -DCMAKE_BUILD_TYPE=Debug ..
      - cmake --build . --config Debug

    artifacts:
      - path: build_imebra_macos/Debug/libimebra.5.*.*.dylib
        name: build_imebra_macos

  -
    matrix:
      only:
        - image: Visual Studio 2015
        - image: Visual Studio 2019

    build_script:
      - cmd: >-

          mkdir build_imebra_release

          cd build_imebra_release
    
          cmake -DCMAKE_BUILD_TYPE=Release ..
    
          cmake --build . --config Release

          ctest -V .

          cd ..

          mkdir build_imebra_release\Release\include
    
          xcopy library\include build_imebra_release\Release\include /s /e

    artifacts:
      - path: build_imebra_release/Release
        name: imebra__vs2015_release

  -
    matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - cmd: >-

          mkdir build_imebra_release

          mkdir build_imebra_debug

          cd build_imebra_release
    
          cmake -DCMAKE_BUILD_TYPE=Release ..
    
          cmake --build . --config Release

          ctest -V .

          cd ../build_imebra_debug
    
          cmake -DCMAKE_BUILD_TYPE=Debug ..
    
          cmake --build . --config Debug

          cd ..

          mkdir build_imebra_release\Release\include
    
          mkdir build_imebra_debug\Debug\include

          xcopy library\include build_imebra_release\Release\include /s /e

          xcopy library\include build_imebra_debug\Debug\include /s /e

    artifacts:
      - path: build_imebra_release/Release
        name: imebra_vs2022_release
      - path: build_imebra_debug/Debug
        name: imebra_vs2022_debug



